#!/bin/bash
# this file demonstrates git fetch
#Project Globus to create timeless off-earth space travel: power systems workings 
echo First working team will be constituted soon
echo Welcome to Project Globus
The project to power off earth travel
